### ISSUE TITLE
iDEP interface improvements

### ISSUE THREAD

**Issue by gexijin** [iDEP-SDSU/idep#115]
The "?" in each page is not noticeable. Some users don't know the existence of the website. 
General improvement of the interface. Access to help info.

**Comment by EricTulowetzke** [comment]
Should we consider using C# or PHP(which has similar syntax to shiny UI code) to create the GUI with? These languages have large frameworks to create nice and user friendly UI.

I will be using PHP with MySQL to create and host a website in one of my classes this semester. I can give more feedback on this idea in May. 

Thank you,
Eric Tulowetzke

**Comment by HalforcNull** [comment]
Instead of using question mark, we could use a image to replace it. ( make it noticeable )

And add an 'on-hover' event to popup the tooltip website. ( acknowledge user the existence of the web site )
One tech solution for on-hover: [link](https://stackoverflow.com/questions/2117046/how-to-show-live-preview-in-a-small-popup-of-linked-page-on-mouse-over-on-link/16625709)

**Comment by EricTulowetzke** [comment]
I like this idea, and next week durian my break I will be making myself start to rewrite iDEP or ShinyGo. I will definitely keep this in mind.

I looked into my suggestion I gave a bit more, and found this htmltools for R: https://cran.r-project.org/web/packages/htmltools/htmltools.pdf

This way if we do find an limitation with the shiny R framework UI, then we can try this above package. 

Thank you,
Eric Tulowetzke
