### ISSUE TITLE
Running iDEP from user's computer using runGitHub

### ISSUE THREAD

**Issue by gexijin** [iDEP-SDSU/idep#2]
Put databases and flat files on servers and enable users to run iDEP on their own computer from RStudio using runGitHub such as:

runGitHub("shiny_example", "rstudio")

**Comment by kruny1001** [comment]
I create another repository for idep-rstudio.  You can check: https://github.com/iDEP-SDSU/iDep-rstudio


```
shiny::runGitHub("iDep-rstudio", "iDEP-SDSU")
```

For running idep-rstudio, execute above code from rStudio. 

***

I also attached install.R script file in order to preinstall required dataset and unzip. 

```
> rscript install.R
```
You can run above command line from `cmd` (windows) or `terminal` (linux or mac)

**Comment by gexijin** [comment]
Currently, we does not support running iDEP in stand alone mode. We may offer this in the future via consulting or other arrangements, which might not be free.
