### ISSUE TITLE
Both server.R and ui.R are empty.

### ISSUE THREAD

**Issue by tyaoi** [iDEP-SDSU/idep#96]
Thanks iDEP develper team for your great efforts and much useful app !

I would like to use iDEP even without connecting to the net.
So, I try installing iDEP locally according to "To run iDEP on your laptop you will need to download the database and follow these instructions" in GitHub.

In step 2,  I moodified and conducted librarySetup.R script using BiocManager::install(version = "3.10") because I use R version 3.6.2 (2019-12-12) on Ubuntu 18.o4. All libraries were successfully installed.

Step 3 and 4 were also conducted. 

In step 5, however, I found both server.R and ui.R are empty. 
When will these scripts be available?

PS.
Although The instruction in GitHub says "Download iDEP source code and example data files from Github", such example data files were also not included in "idep-master".

**Comment by HalforcNull** [comment]
Hi tyaoi,

Thank you for reaching out. The readme file is out of date. 

Server.R and ui.R file is under idep/shinyapps/idep90/ folder. 
Since you already setup the library, please try following steps:

1. Create a 'data' folder under idep/ folder.

2. Download [pathwayDB](https://sdsu.box.com/shared/static/c24f792ojoikpzu0lkpng8uuf9ychwm7.gz), [Motif](https://sdsu.box.com/shared/static/9v1ao6mwhduvrcx793j3answph9gqnkt.gz), [geneInfo](https://sdsu.box.com/shared/static/mns0k1uvwtfnsohoc89b984ih36nmnz9.gz), [data_go](https://sdsu.box.com/shared/static/qwpdh36vcisgy1hcmadck8i8ezhvr2fh.gz), [convertIDs](https://sdsu.box.com/shared/static/sorewt7w6iypmhg2k2xhyi8myeit156o.gz)

3. Unzip downloaded files, move them into idep/data/data96/ folder. 
So you have:
idep/data/data96/data_go (folder)
idep/data/data96/geneInfo  (folder)
idep/data/data96/motif (folder)
idep/data/data96/convertIDs.db (file)

4. Navigate to idep/shinyapps/idep90/ folder

5. Start shiny app

**Comment by tyaoi** [comment]
Thanks quick response, HalforcNull  !!

I immediately tried to continue the process.
I downloaded the data, and unzipped the files using commands(gunzip and tar) .
Now I have the followings:
~/tool/iDEP90_standAlone/idep-master/data/data96
├── Motif
├── convertIDs.db
├── data_go
├── geneInfo
└── pathwayDB


On the otherhand, shiny app locate here:
~/tool/iDEP90_standAlone/idep-master/shinyapps/idep90
├── fb.js
├── ga.js
├── iDEP_core_functions.R
├── readme.md
├── server.R
├── ui.R
└── www

Next,  I started RStudio and run the following commands:

setwd("~/tool/iDEP90_standAlone/idep-master")
shiny::runApp("shinyapps//idep90", launch.browser = TRUE)

After chromium browser started and opened the initial screen of iDEP90, the console panel returned the error message: cannot open the file '../../data/data96/data_go/STRING11_species.csv'.
Actually, I confirmed that:
$ $ ls ~/tool/iDEP90_standAlone/idep-master/data/data96/data_go
BcellGSE71176_p53.csv             GSE37704_sailfish_genecounts.csv
BcellGSE71176_p53_sampleInfo.csv  KEGG_Species_ID.csv

Did I mistake the way to do in RStudio ?

tyaoi

**Comment by HalforcNull** [comment]
Hi tyaoi,

Thank you for the detailed error message.
I'm afraid the data base we provided may also out of date. 

We should have the new version somewhere, but I need to contact with @gexijin to grab the latest version.
I will send you an update once we had the link.

In the mean time, if you need use iDEP, please try access http://bioinformatics.sdstate.edu/idep/ .

Thank you again for the comment.

HalforcNull

**Comment by HalforcNull** [comment]
Hi @tyaoi,

Just talked with @gexijin.
"It’s more complicated than that."
He is going to run a whole set of programs fix this issue later this month.

Best,

HalforcNull

**Comment by tyaoi** [comment]
Hi @HalforcNull 

I've acknowledged !!

The app is useful not only for analyzing data of mine, but also as a tool for teaching graduate students, who are new in RNA-seq analysis, to  the basics.

That was unexpected, but I'm using web-version and waiting for the issue to be resolved.

Thanks!

**Comment by HalforcNull** [comment]
Hi @tyaoi ,

It is exciting to know you are using this tool for teaching.
Just for your information, there's a document @gexijin created. This document includes many detail about this tool. And here is the link: https://idepsite.wordpress.com/ 

Best,

HalforcNull

**Comment by tyaoi** [comment]
Thank you !!
